ALTER TABLE billing
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS favour_of TEXT,
  ADD COLUMN IF NOT EXISTS cheque_number TEXT,
  ADD COLUMN IF NOT EXISTS cheque_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS gpay_reference TEXT;
